### ISSUE TITLE
How to listen to events?

### ISSUE THREAD

**Issue by bdrtsky** [Developmint/nuxt-webfontloader#10]
For example, I need to listen to `fontactive` event. How I can do that using this plugin? 
Using vanilla `webfoantloader` is no good since it throws window error. But I am not sure how to use events with this plugin? Is this possible?

**Comment by manniL** [comment]
@bdrtsky see https://github.com/Developmint/nuxt-webfontloader/issues/5

**Comment by bdrtsky** [comment]
@manniL I actually need to use it inside Vue component, not in `nuxt.config.js`. Is this possible?
