### ISSUE TITLE
Multiple font weights wrong request url

### ISSUE THREAD

**Issue by TheDiehard22** [Developmint/nuxt-webfontloader#13]
When using multiple font weights the request url is invalid.

`webfontloader: {
    google: {
      families: ['Open+Sans+Condensed:700|Open+Sans:400,700'],
    },
  },`

This configuration should give me:
https://fonts.googleapis.com/css?family=Open+Sans+Condensed:700|Open+Sans:400,700
and not this:
https://fonts.googleapis.com/css?family=Open+Sans+Condensed:700|Open+Sans&subset=400,700

**Comment by manniL** [comment]
Better report that to https://github.com/typekit/webfontloader ☺️
