### ISSUE TITLE
Typekit - how?

### ISSUE THREAD

**Issue by simplenotezy** [Developmint/nuxt-webfontloader#42]
How can I use typekit and also leverage font-swap? It's not documented as far as I can see, so I thought I'd ask.

**Comment by isuke01** [comment]
Hey, just use webfontloader docs 
https://www.npmjs.com/package/webfontloader
it works as docs says, but just put it inside your nuxt config :)
```
webfontloader: {
      typekit: {
        id: 'xxxxx'
      }
    },
```

**Comment by TheAlexLichter** [comment]
I'm not sure whether Typekit actually support font-swap atm. But as @isuke01 said, that's probably a good question for https://github.com/typekit/webfontloader
