### ISSUE TITLE
Event callback functions throw compiler error

### ISSUE THREAD

**Issue by wagerfield** [Developmint/nuxt-webfontloader#5]
I am getting compiler errors when specifying [event callback functions](https://github.com/typekit/webfontloader#events) in the `webfontloader` options object:

```js
// nuxt.config.js
export default {
  modules: [
    "nuxt-webfontloader"
  ],
  webfontloader: {
    google: {
      families: ["Roboto+Mono:400,700"]
    },
    active() {
      console.log("active")
    }
  }
}
```

Looking at the implementation of this module, I think this is because the web font loader `options` are [serialised](https://github.com/Developmint/nuxt-webfontloader/blob/master/lib/plugin.template.js#L4) before they are passed to `WebFont.load`.

Since Nuxt is transpiling `nuxt.config.js` into ES5, you get "Syntax Error: Unexpected token" error.

If I replace the `active() {}` shorthand method with a longhand ES5 `active: function() {}` I get further errors in the console saying "Uncaught (in promise) ReferenceError: _7e6‍ is not defined". Again, I expect this is due to the function being transpiled and serialised.

Thanks in advance!

**Comment by manniL** [comment]
I've added a test to the test suite to cover `webfontloader`'s event callbacks

I tried the following things locally:

```js
loading: () => {
  window._fontsAreLoading = true
}
```

**Works!**

---

```js
loading() {
  window._fontsAreLoading = true
}
```

Can't be serialized

---
```js
loading: function () {
  window._fontsAreLoading = true
}
```

**Works!**

Also be aware that you can't use imported packages from your `nuxt.config.js` in these functions.

Hope that helps ☺️
